### ISSUE TITLE
replace usages of Property.once()

### ISSUE THREAD

**Issue by jbphet** [phetsims/area-builder#104]
We have decided to remove support for `Property.once()`.  This simulation is the only one that uses it, so usages should be replaced with alternatives.  The parent issue is https://github.com/phetsims/axon/issues/129.

Once done, I should remove `once` from Property.js.

**Comment by jbphet** [comment]
I've removed the usages of Property.once from Area Builder, then removed the definition from Property.js.  I also removed Events.once from Events.js, just to be thorough and make sure there are no usages of .once() our sim code.  I verified that the Axon and Scenery unit tests passed after doing this, and also spot checked a handful of simulations.

Assigning to @samreid to inspect the changes, especially the ones to axon/tests/quint/js/events.js (I was a bit less confident about these).

**Comment by samreid** [comment]
Skimming the change sets, searching for `.once(` and checking bayes all seem promising, thanks.  Closing.
