### ISSUE TITLE
evaluate stepper option to Carousel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/area-builder#106]
Carousel was converted to use TWIXT/Animation in https://github.com/phetsims/sun/issues/381.  The default is `stepper: 'manual'`, which means that the client must call `step` to control the Carousel's animation.   To avoid having to make changes in this sim, `stepper: 'timer'` was added to Carousel call sites, which means that the animation will run automatically using the sim Timer.  

The responsible developer should evaluate what `stepper` value should be used.

**Comment by jbphet** [comment]
I've looked at the code, and I think I'll leave the `stepper` value set to `timer`.  This is pretty much how the original implementation worked, and the carousel isn't tracked as a property or variable inside `AreaBuilderGameView`, and it doesn't seem to me to be worthwhile to change this.  I tested it on master and the carousel appears to work fine.  Closing.
