### ISSUE TITLE
Usability on small screens review

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/area-builder#110]
Per @kathy-phet's request in https://github.com/phetsims/QA/issues/295 I am making issues in each published sim repo detailing the pointer areas and usability of sims on phone sized screens.  Done on an iPhone 7 iOS 12 device.

Potential Difficulties Noticed:
* Very strange looking leftover pointer areas of blocks when switching scenes on the first screen.  Pictured below
* plus/minus buttons at top of screen were sometimes hard to press

Screenshots:
![Image from iOS (1)](https://user-images.githubusercontent.com/41024075/56068802-6a573880-5d3d-11e9-8353-667fb846e6f8.png)
![Image from iOS (2)](https://user-images.githubusercontent.com/41024075/56068803-6aefcf00-5d3d-11e9-8410-4b0710f5d01e.png)
![Image from iOS (3)](https://user-images.githubusercontent.com/41024075/56068805-6aefcf00-5d3d-11e9-9817-de1a481d3df9.png)
![Image from iOS (4)](https://user-images.githubusercontent.com/41024075/56068806-6aefcf00-5d3d-11e9-92d1-47cf1a2b2328.png)
![Image from iOS](https://user-images.githubusercontent.com/41024075/56068807-6aefcf00-5d3d-11e9-9b78-21565f0bb830.png)

**Comment by amanda-phet** [comment]
I agree those accordion box buttons are tricky on phones. This is likely the case for all accordion boxes, right? Since we have the space, I think it would be nice to increase those. Assigning @jbphet to make that change. 

As for the leftover touch areas, a quick search in past area-model issues shows that this is a known "issue" but doesn't cause any usability issues. See https://github.com/phetsims/area-builder/issues/89.

**Comment by SaurabhTotey** [comment]
The touch areas that show up for invisible blocks can be safely ignored I think. In addition to #89, this seems all very similar to https://github.com/phetsims/circuit-construction-kit-dc/issues/178 and https://github.com/phetsims/balancing-act/issues/87 to me. The touch areas show, but aren't actually usable unless the relevant elements are present.

In my latest commit, increased the touch dilation area for the accordion boxes so they look like the picture below.
<img width="1440" alt="Screen Shot 2019-06-27 at 3 44 58 PM" src="https://user-images.githubusercontent.com/22577113/60303027-9de44080-98f2-11e9-824e-c07d1a3cc5ac.png">
<img width="1440" alt="Screen Shot 2019-06-27 at 3 44 51 PM" src="https://user-images.githubusercontent.com/22577113/60303045-a6d51200-98f2-11e9-8ab9-087c6cea0c1b.png">

**Comment by amanda-phet** [comment]
Thanks @SaurabhTotey I think those larger areas look like a nice improvement.
