### ISSUE TITLE
bad require statement

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/area-builder#112]
AreaBuilderSharedConstants.js:

```js
  INVALID_VALUE: require( 'string!AREA_BUILDER/invalidValue' )
```

This `require` violates PhET conventions and will not be properly handled by ES6 migration tools. You'll need to pull this out into a `const` statement:

```js
const invalidValueString = require( 'string!AREA_BUILDER/invalidValue' );
...
  INVALID_VALUE: invalidValueString
```

Priority high, since ES6 migration will be occurring soon.

**Comment by zepumph** [comment]
See https://github.com/phetsims/chipper/issues/849 as the parent/duplicate issue.
