### ISSUE TITLE
migrate KeyPad to common code?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/area-builder#46]
KeyPad looks like a prime candidate for migration to common code.

**Comment by jbphet** [comment]
Keypad.js has been consolidated with the version that was in Arithmetic and moved to common code, see commits listed above for details.  I haven't done a lot of work trying to anticipate what other potential users of this might need for options.  I don't know of any sims on the horizon that intend to use this, so maybe we leave it as is and assume future users will add any needed features. Assigned to @pixelzoom to review the code and to comment on whether to put effort into further generalization.

**Comment by pixelzoom** [comment]
Overall looks good, and no we should defer further generalization and features until more sims use this. A couple of comments on the current implementation:

(1) Function createNumberKey should be moved out of the constructor.

(2) The name Keypad is too general. This is a keypad specifically used for numeric entry. So perhaps NumberKeypad or CalculatorKeypad. 

Back to @jbphet.

**Comment by pixelzoom** [comment]
Also note this issue in scenery-phet: https://github.com/phetsims/scenery-phet/issues/55

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/scenery-phet/issues/55, functionality requirements were listed for the key pad.  Does this implementation meet those requirements?  Can that issue be closed?

**Comment by pixelzoom** [comment]
Above I said:
> we should defer further generalization and features until more sims use this.

But in https://github.com/phetsims/scenery-phet/issues/55, functionality requirements were listed for the key pad.  So perhaps you should the creator of that issue (@ariel-phet) about whether features should be added now or later.

**Comment by jbphet** [comment]
I want with NumberKeypad for the name, since "numeric keypad" seems to have a specific definition (see https://en.wikipedia.org/wiki/Numeric_keypad) and CalculatorKeypad seemed overly specific.

**Comment by jbphet** [comment]
This issue is addressed, closing.
