### ISSUE TITLE
Level 5 game syntax and color icons

### ISSUE THREAD

**Issue by patricialoeblein** [phetsims/area-builder#6]
![image](https://cloud.githubusercontent.com/assets/5091205/4035523/d6494e1c-2c90-11e4-87a0-8d58e4ff302b.png)

I think the use of the comma seems incorrect. Perhaps a colon or semi-colon ? I think a colon is more widely used, therefore I like it, but I don't know if there is a math use with which might add to the confusion. 

Also, I am not a fan of the oval for color identification. Is there a less "shape" thing we could use like the bucket pouring color that is used in paint?
![image](https://cloud.githubusercontent.com/assets/5091205/4035610/9aaeec3a-2c91-11e4-93ef-1d0e410b38df.png)

**Comment by jbphet** [comment]
This is an old issue, and V2 is not on the horizon, and it seems to work well as is.  Closing.
