### ISSUE TITLE
Poor rendering of happy face in game home screen game Icon

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/area-builder#68]
Test device: MacBook Pro
Operating System: OSX 10.9.4
Browser: Chrome 37.0.2062.124

Severity: Very Low Priority. Just thought to make a note.

Screenshots:
![screen shot 2014-09-30 at 12 12 47 pm](https://cloud.githubusercontent.com/assets/5631059/4463785/296f231a-48ce-11e4-8ce3-ae1a25bb983b.png)

Troubleshooting information (do not edit):
Name: Area Builder
URL: http://www.colorado.edu/physics/phet/dev/html/area-builder/1.0.0-rc.4/area-builder_en.html
Version: 1.0.0-rc.4
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36
Language: en-US
Window: 1279x610
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by phet-steele** [comment]
@jbphet the issue is still there but is hardly noticeable (more so some devices than others). Your call, Sir! Win 10 FF for example:

![areaface](https://cloud.githubusercontent.com/assets/5863899/15220428/be167b2c-1824-11e6-8bd1-81d84a56e079.PNG)

**Comment by alynne-phet** [comment]
@jbphet This is what it looks like in 10.9.5 in Chrome. 
![image](https://cloud.githubusercontent.com/assets/19288972/15221546/18b48e94-1829-11e6-978f-74d50051f367.png)

**Comment by jbphet** [comment]
I looked at a recently released sim that has fairly elaborate icons - Forces and Motion Basics - and found that the icons were slightly higher resolution than those used in Area Builder, so I re-exported the icons at the higher resolution and made sure to export with the "Art Optimized" option.  This should improve things a bit.

**Comment by phet-steele** [comment]
Sure, at this point you'd only notice it if you knew it was there.
