### ISSUE TITLE
Properties should have `Property` suffix

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/area-builder#74]
If we're going to do this for beers-law-lab (https://github.com/phetsims/beers-law-lab/issues/86), then let's do it for all sims.

Some anti-pattern examples from this sim (not exhaustive):

> AreaAndPerimeterDisplay: this.expanded = new Property( true );
> ShapeCreatorNode: var createdCount = new Property( 0 )

**Comment by jbphet** [comment]
Implemented, assigning to @pixelzoom for verification.

**Comment by pixelzoom** [comment]
:+1: Closing.
