### ISSUE TITLE
bad URL for marching squares algorithm

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/area-builder#76]
Ran across this while searching the PhET HTML5 code base for potential 3rd-party software.

ShapePlacementBoard.js contains this comment:

```js
/**
 * Marching squares algorithm for scanning the perimeter of a shape, see
 * http://devblog.phillipspiess.com/2010/02/23/better-know-an-algorithm-1-marching-squares/
 * @private
 */
```

This URL results in "ERR_EMPTY_RESPONSE" (Chrome).  So either there's a typo, or the URL is stale.

**Comment by jbphet** [comment]
Looks like the URL is just stale.  I've changed it to reference a Wikipedia article, since that's more likely to be around in the future.  The new comment looks like this:

```
    /**
     * Marching squares algorithm for scanning the perimeter of a shape, see
     * https://en.wikipedia.org/wiki/Marching_squares or search the Internet for 'Marching Squares Algorithm' for more
     * information on this.
     * @private
     */
```

Closing.
