### ISSUE TITLE
unnecessary calls to LayoutBox.updateLayout

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/area-builder#77]
... in AreaBuilderControlPanel and AreaBuilderScoreboard, in this case the VBox subtype of LayoutBox.

For example, in AreaBuilderControlPanel:

```js
    // Add/remove the grid visibility control.
    this.visibilityControls.gridControlVisibleProperty.link( function( gridControlVisible ) {
      if ( gridControlVisible && !vBox.isChild( gridCheckbox ) ) {
        vBox.insertChild( 0, gridCheckbox );
      }
      else if ( !gridControlVisible && vBox.isChild( gridCheckbox ) ) {
        vBox.removeChild( gridCheckbox );
      }
      vBox.updateLayout();
    } );
```

LayoutBox overrides insertChild and removeChildWithIndex (which is called by removeChild). So the call to updateLayout should be unnecessary.  If it is necessary, then that would indicate a bug in LayoutBox.

**Comment by jbphet** [comment]
I removed the calls and tested, and the sim appears to work fine, so it does seem like the calls were unnecessary.  Closing.
