### ISSUE TITLE
Game: clicking eraser button doesn't make "Try Again" button disappear

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/area-builder#80]
As noted in ![screenshot_584](https://cloud.githubusercontent.com/assets/3046552/9552383/c7d6ca3e-4d74-11e5-884d-70bd90362627.png)... 

Interacting with specific things in the Game makes the "Try Again" button disappear. And it seems to be limited to things that change the user's "answer" in some way.  For example, in Level 1 (screenshot) below, moving any blue square makes the "Try Again" button disappear, but toggling check boxes does not.

If this is indeed the desired behavior, then the eraser button seems to be buggy. It changes the user's answer, but the "Try Again" button does not disappear.

There may be other things like this in other types of challenges. I've only noted this one example.

![screenshot_584](https://cloud.githubusercontent.com/assets/3046552/9552496/c6102a46-4d75-11e5-8a5d-14184c319760.png)

**Comment by pixelzoom** [comment]
I looked through all 6 game levels, and the eraser button appear to be the only problem.

**Comment by pixelzoom** [comment]
Discussed with @jbphet.  

For the challenges that have a calculator, the user's answer is what's in the calculator, and the boxes you can drag around are aids to help you think about the area.  So I think it's appropriate that the eraser button doesn't make the "Try Again" button disappear, because it's not changing the user's answer.

But in the challenges where the user's answer is the number of boxes they've dragged in (levels 1 & 2?), pressing the eraser button does change the user's answer. The "Try Again" button should therefore disappear and be replaced with a (disabled) "Check" button.

**Comment by amanda-phet** [comment]
I agree with the above comment. 
>But in the challenges where the user's answer is the number of boxes they've dragged in (levels 1, 2, 5 & 6?), pressing the eraser button does change the user's answer. The "Try Again" button should therefore disappear and be replaced with a (disabled) "Check" button.

If it is significantly easier to implement this behavior for all levels (including 3-4 which are keypad challenges) then I don't think we should work too hard around this specification.

**Comment by jbphet** [comment]
Should now be fixed, I'll have the QA team verify on the next release candidate.

**Comment by phet-steele** [comment]
Looks fixed in 1.1.0-rc.1.
