### ISSUE TITLE
maintenance issues with HCarousel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/area-builder#81]
Noted while working on https://github.com/phetsims/sun/issues/166 (create a Carousel component). HCarousel is the closest in appearance to what's desired, so I decide to start here. These are maintenance/reuse issues that are making it difficult to modify/generalize.

(1) Path for the arrows is duplicated. The shape of these arrows if the same, only their orientation is different. So why is there totally different shapes?  Create one shape that can be rotated/reflected to the correct orientation, using Shape.transformed.

```js
var nextIcon = new Path( new Shape().moveTo( 0, 0 ).lineTo( ARROW_WIDTH, ARROW_HEIGHT / 2 ).lineTo( 0, ARROW_HEIGHT ), iconOptions );
var previousIcon = new Path( new Shape().moveTo( ARROW_WIDTH, 0 ).lineTo( 0, ARROW_HEIGHT / 2 ).lineTo( ARROW_WIDTH, ARROW_HEIGHT ), iconOptions );
```

(2) Options for arrow buttons are duplicated. The only things different here is options.content. Factor out what's common and use _.extends.

```js
    var nextButton = new RectangularPushButton( {
      content: nextIcon,
      xMargin: BUTTON_X_MARGIN,
      buttonAppearanceStrategy: RectangularButtonView.flatAppearanceStrategy,
      baseColor: BUTTON_BASE_COLOR,
      cornerRadius: CORNER_RADIUS,
      minHeight: panelHeight,
      centerY: panelHeight / 2
    } );
    var previousButton = new RectangularPushButton( {
      content: previousIcon,
      xMargin: BUTTON_X_MARGIN,
      buttonAppearanceStrategy: RectangularButtonView.flatAppearanceStrategy,
      baseColor: BUTTON_BASE_COLOR,
      cornerRadius: CORNER_RADIUS,
      minHeight: panelHeight,
      centerY: panelHeight / 2
    } );
```

**Comment by pixelzoom** [comment]
(3) Magic number `4` in AreaBuilderGameView just happens to be the default value for HCarousel `options.numVisibleAtOnce`.  If this changes (or when HCarousel is replaced by sun.Carousel), this will be promoted to a bug.  Here's the problem code:

```js
     if ( creatorNodes.length > 4 ) {
            // Add a scrolling carousel.
            this.shapeCarouselRoot.addChild( new HCarousel( ... ) );
```

**Comment by pixelzoom** [comment]
Assigning to @jbphet since https://github.com/phetsims/area-builder/issues/81#issuecomment-140180208 has a high probability of becoming a bug.

**Comment by pixelzoom** [comment]
(4) The use of Tween doesn't follow the pattern used in other PhET sims, and results in a copy of all properties for the node passed to the constructor. 

 In HCarousel:

```js
new TWEEN.Tween( scrollingNode ).to( { left: targetPositionProperty.value * scrollDistance }, 400 ).easing( TWEEN.Easing.Cubic.InOut ).start();
```

Tween's constructor copies *all* properties of the animated object, in this case a Node. That's why we typically use this pattern:

```js
var someNode = ...
var parameters = { opacity: 0 }; 
var tween = new TWEEN.Tween( parameters )
      .to( { opacity: 1 }, 500 )
      .onUpdate( function() {
        someNode.opacity = parameters.opacity;
      } )
...
```

**Comment by pixelzoom** [comment]
(5) There's no management of the Tween animation.  On multitouch, it's possible to get 2 animations running simultaneously.  Before starting an animation, you need to stop any animation that is in progress.  See https://github.com/phetsims/tasks/issues/358.

**Comment by pixelzoom** [comment]
@jbphet Here's how you can address (4) and (5) above:

```js
var tweenInstance;
 targetPositionProperty.link( function( pos ) {
      ...
    
      // Stop any animation that's already running.
      tweenInstance && tweenInstance.stop();

      // Set up the animation to scroll to the next location.
      var parameters = { left: scrollingNode.left };
      tweenInstance = new TWEEN.Tween( parameters )
          .easing( TWEEN.Easing.Cubic.InOut )
          .to( { left: -scrollIndex * scrollingDelta }, 400 )
          .onUpdate( function() { scrollingNode.left = parameters.left; } )
          .start();
} );
```

**Comment by pixelzoom** [comment]
Btw... about this line:

`tweenInstance && tweenInstance.stop();`

According to the Tween documentation, calling `stop` on a tween that has already completed is a no-op.

**Comment by pixelzoom** [comment]
Or it may be better to just ignore all of the above and use sun.Carousel, see https://github.com/phetsims/sun/issues/166.

**Comment by jbphet** [comment]
The HCarousel has been replaced with the new common code carousel, so the potential problems described above have been addressed.  Closing.
