### ISSUE TITLE
ShapeCreatorNode nits

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/area-builder#83]
While working on Function Builder, I looked at ShapeCreateNode for inspiration.  I noticed a few nits that I thought I'd mention, since they affected my ability to understand the code.   Up to you whether to address either (or neither) of these.

(1) parent ScreenView

In this bit of code (line 97):

```js
        // Find the parent screen by moving up the scene graph.
        var testNode = self;
        while ( testNode !== null ) {
          if ( testNode instanceof ScreenView ) {
            this.parentScreen = testNode;
            break;
          }
          testNode = testNode.parents[ 0 ]; // Move up the scene graph by one level
        }
```

The comments and var name indicate that we're looking for a Screen, when in fact we're looking for a ScreenView.  Recommended to rename `this.parentScreen` to `this.parentScreenView` and adjust doc.

This bit of code is called every time a drag starts.  Unless you plan on moving this Node between ScreenViews (unlikely), it's only necessary to find the parent ScreenView the first time a drag is initialized.  Recommended to wrap the above code in `if ( !this.parentScreenView ) { ... }`.

Could also use an assertion that verifies that you actually found a parent ScreenView.

(2) Test for unit square

Next is this bit of code:

```js
 if ( options.creationLimit < Number.POSITIVE_INFINITY &&
         ( shape.bounds.width !== AreaBuilderSharedConstants.UNIT_SQUARE_LENGTH ||
           shape.bounds.height !== AreaBuilderSharedConstants.UNIT_SQUARE_LENGTH ) ) {
 // The ability to set a creation limit ONLY works for unit squares.  The reason for this is that non-unit shapes
...
```

This is a dubious method of testing for a unit square.  A circle with diameter === AreaBuilderSharedConstants.UNIT_SQUARE_LENGTH would also pass the test.  Not an issue with the sim's current feature set, but a potential landmine for anyone enhancing the sim in the future.  A better approach might be to have a type hierarchy of Shape (UnitSquare, ...) and test that `shape instanceof UnitSquare`.

**Comment by jbphet** [comment]
I elected to implement the suggestions described in 1 above, but not those in 2.  My reasoning for not doing 2 is that I feel it is unlikely to cause future problems, it's well documented, and it would require more time than it's worth to implement a type hierarchy that would make this situation easier to detect.

I looked through the code base, and very similar code exists in a number of other simulations.  I will discuss with the team and will either generalize this functionality or will implement the same changes in all copies.  For this particular issue, however, the work is done.  Closing.

**Comment by pixelzoom** [comment]
Reopening.  

Recommendation (1) in https://github.com/phetsims/area-builder/issues/83#issue-122088450 was to search for the parent ScreenView once, instead of at the start of every drag.  That's buggy in balancing-act.ModelElementCreatorNode.  Here's the related code:

```js
start: function( event ) {
  if ( !parentScreenView ) {
    ...
    parentScreenView = testNode;
  }
},
 
end: function( event ) {
  ...
  parentScreenView = null;
}
```

By setting `parentScreenView = null` at the end of a drag, you're causing a search for `parentScreenView` at the start of every drag.

**Comment by jbphet** [comment]
Wow, good eye.  Weird that it was only in this sim and not any of the others.  At any rate, I've removed the offending line.  Good to close now @pixelzoom?
