### ISSUE TITLE
Text overlaps with &stringTest=double

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/area-builder#85]
Testing on Personal Mac 10.11
Safari 9.0
Text in the PhET menu overlap
<img width="540" alt="screen shot 2016-01-19 at 9 42 50 am" src="https://cloud.githubusercontent.com/assets/5631059/12425267/3480832c-be91-11e5-9ad5-9ddf55b73f8e.png">

And text in the area and perimeter counter also over lap
<img width="344" alt="screen shot 2016-01-19 at 9 42 56 am" src="https://cloud.githubusercontent.com/assets/5631059/12425279/4914337e-be91-11e5-813e-0aae53755902.png">
Troubleshooting information (do not edit):
Name: ‪Area Builder‬:‪Area Builder‬
URL: http://phettest.colorado.edu/area-builder/area-builder_en.html?ea&brand=phet&stringTest=double
Version: 1.1.0-dev.1 (require.js)
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56
Language: en-us
Window: 1240x712
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (2.1 INTEL-10.8.77)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
Testing for Task https://github.com/phetsims/tasks/issues/479

**Comment by orejolaphet** [comment]
Issue seems exclusive to safari, tested this on both chrome and firefox and this issue did not occur.

**Comment by phet-steele** [comment]
This is certainly https://github.com/phetsims/scenery/issues/469, and is not fixed in 1.1.0-rc.1 (nor needs to be). Closing as per the linked issue.
