### ISSUE TITLE
Can drag squares out of dev boundaries

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/area-builder#86]
Test device: Personal Mac
Operating System: OSX 10.11
Browser: Safari 9
Problem description: You can drag the tiles out of the dev boundaries
Severity: Low

Screenshots:
<img width="1046" alt="screen shot 2016-01-19 at 9 52 52 am" src="https://cloud.githubusercontent.com/assets/5631059/12425586/b06dc886-be92-11e5-8d89-448573cab13c.png">

Troubleshooting information (do not edit):
Name: ‪Area Builder‬
URL: http://phettest.colorado.edu/area-builder/area-builder_en.html?ea&brand=phet&dev
Version: 1.1.0-dev.1 (require.js)
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56
Language: en-us
Window: 1240x712
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (2.1 INTEL-10.8.77)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

Testing for task https://github.com/phetsims/tasks/issues/479

**Comment by phet-steele** [comment]
Things are bounded!
