### ISSUE TITLE
Lots of text overlapping with stringTest=long

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/area-builder#88]
Test device: Dirac

Operating System: OS X 10.11.2

Browser: Chrome

Problem description: Using stringTest=long causes a lot of overlapping text and buttons in the game section. However all of the buttons and checkboxes are still clickable even if they are covered up by other textboxes.

Screenshots:
![screen shot 2016-01-20 at 12 06 25 pm](https://cloud.githubusercontent.com/assets/11947677/12460020/da483ac4-bf6e-11e5-9779-150b730b5789.png)

Even though the show grid checkbox is entirely covered up, it can still be clicked.

Troubleshooting information (do not edit):
Name: 12345678901234567890123456789012345678901234567890
URL: http://phettest.colorado.edu/area-builder/area-builder_en.html?ea&brand=phet&stringTest=long
Version: 1.1.0-dev.1 (require.js)
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
Language: en-US
Window: 1115x582
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

For phetsims/tasks#479

**Comment by phet-steele** [comment]
Saw this issue after #87. Been tracking string issues there, closing this one.
