### ISSUE TITLE
Strange showPointerAreas behavior 

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/area-builder#89]
Test device: Dirac

Operating System: OS X 10.11.2

Browser: Chrome 

Problem description: Using showPointerAreas in the explore section, when you switch between the slider options of one workspace or two, the pointer area boxes around any squares you put down will still show after you switch the slider. 

Steps to reproduce: With showPointerAreas on, go into Explore, put down some squares in the workspace and then click the slider to switch to two workspaces. The pointer area squares will still be there from before. If you place any new squares, and switch back, they will also show up.

Screenshots:
![screen shot 2016-01-20 at 12 48 24 pm](https://cloud.githubusercontent.com/assets/11947677/12461066/3bf13546-bf74-11e5-8bc3-192c003fa5ca.png)
![screen shot 2016-01-20 at 12 48 39 pm](https://cloud.githubusercontent.com/assets/11947677/12461071/3eda31cc-bf74-11e5-969a-ee797aa3914c.png)
![screen shot 2016-01-20 at 12 48 51 pm](https://cloud.githubusercontent.com/assets/11947677/12461083/4c4a5e90-bf74-11e5-8583-8638df244387.png)

Troubleshooting information (do not edit):
Name: ‪Area Builder‬
URL: http://phettest.colorado.edu/area-builder/area-builder_en.html?ea&brand=phet&showPointerAreas
Version: 1.1.0-dev.1 (require.js)
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
Language: en-US
Window: 1115x582
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

For phetsims/tasks#479

**Comment by jbphet** [comment]
I agree that this looks a little strange, but it doesn't affect the operation of the sim for normal use cases.  I think this is just an indication that Scenery perhaps doesn't handle this case well for invisible objects, but I don't think it's a big deal.  Closing.
