### ISSUE TITLE
?showPointerAreas could be optimized

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/area-builder#93]
A quick review of ?showPointerAreas on 1.1.0-rc.1suggested that several pointer areas could be expanded such as 
- reset all button
- eraser button
- check button (game)
- start over button (game)
- sound and timer button (game) -- perhaps should be expanded by default in vegas?

**Comment by jbphet** [comment]
I expanded touch areas in the recommended places.  I did *not* change the defaults in vegas - we had a discussion about this a while back and decide optimal defaults were too hard to come up with and we should stick with no dilation by default on common buttons.

**Comment by jbphet** [comment]
It wasn't requested in this issue, but I also enlarged the button in the accordion box that contains the perimeter and area display.

**Comment by jbphet** [comment]
Assigning back to @ariel-phet in case he'd like to pull the current master and take a look.  If so, and if it looks good, please go ahead and close it.  If you don't want to take the time, please unassign and I'll have the QA team test on the next RC.

**Comment by ariel-phet** [comment]
Current pull of area builder is not loading. Getting the following error:

```
require-2.1.11.js:1895 GET http://localhost/gitdev/area-builder/js/TANDEM/scenery/input/TandemDragHandler.js?bust=1462837104454 req.load @ require-2.1.11.js:1895context.load @ require-2.1.11.js:1639Module.load @ require-2.1.11.js:820Module.fetch @ require-2.1.11.js:810Module.check @ require-2.1.11.js:840Module.enable @ require-2.1.11.js:1143context.enable @ require-2.1.11.js:1511(anonymous function) @ require-2.1.11.js:1128(anonymous function) @ require-2.1.11.js:132each @ require-2.1.11.js:57Module.enable @ require-2.1.11.js:1090Module.init @ require-2.1.11.js:774callGetModule @ require-2.1.11.js:1170context.completeLoad @ require-2.1.11.js:1544context.onScriptLoad @ require-2.1.11.js:1671
require-2.1.11.js:166 Uncaught Error: Script error for: TANDEM/scenery/input/TandemDragHandler
http://requirejs.org/docs/errors.html#scripterror
```

Tried a few other sims, working fine (balancing act, under pressure)

**Comment by ariel-phet** [comment]
ah...this appears to be some sort of caching error I was encountering, cleared cache and sim runs fine now (thanks for the pro tip @phet-steele).

All changes to pointer areas look good. Closing
