### ISSUE TITLE
Perimeter label encroaches upon the Values panel

### ISSUE THREAD

**Issue by phet-steele** [phetsims/area-builder#94]
@ariel-phet @jbphet perimeter values directly underneath the Values panel are overlapping. Not by a significant amount sure, but I do think we have the real estate to move things up or down by a few pixels and make this look better. I see this on iPads, Win 10, and OSX browsers (with lots of different resolutions and dimensions).

![perimpan](https://cloud.githubusercontent.com/assets/5863899/15127597/8c3a57ea-15f4-11e6-9d6b-031d4f09f0f5.PNG)

Also in the published version. For phetsims/tasks/issues/588.

**Comment by ariel-phet** [comment]
Here is a subtle adjustment that I think will do the trick. Everything in play area moved vertically down a few pixels and a little more spacing between board and area/perimeter readout

![area](https://cloud.githubusercontent.com/assets/4051174/15159828/c71aa382-16b3-11e6-86bc-fc1700cd461f.PNG)

**Comment by jbphet** [comment]
I just did a bit of testing on the currently published version, and the same problem exists on the lower portions of the sim.  @ariel-phet and I discussed, and the plan is for me to move things around until the problem goes away.

Here's a screenshot of the issue on v1.0.1, which is the published version as of this writing:
![ab-cutoff](https://cloud.githubusercontent.com/assets/3082831/15186862/f6a17c90-175b-11e6-8d22-bb3f14a679b6.PNG)

**Comment by jbphet** [comment]
I've made some adjustments, here are a couple of screen shots:

![ab-cutoff-fix-1](https://cloud.githubusercontent.com/assets/3082831/15192668/7e215b52-1777-11e6-8ea2-36d6412ecada.PNG)


![ab-cutoff-fix-2](https://cloud.githubusercontent.com/assets/3082831/15192669/7e27eea4-1777-11e6-8f3f-3859a1415117.PNG)

**Comment by phet-steele** [comment]
Fixed!
