### ISSUE TITLE
issues with the "Reset All" button

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/area-builder#97]
Noted while investigating https://github.com/phetsims/scenery-phet/issues/41.

Misc issues with the "Reset All" button in area-builder:

• the button size is different for the 2 screens (radius: 20 vs 22)

• the button changes position when switching screens, something that I believe PhET tries to avoid, and there doesn't appear to be any reason for it in this case

**Comment by jbphet** [comment]
I've re-positioned and resized the reset button, and removed a lineWidth option, so that now the buttons look and are positioned the same between screens.  Closing.
